alias	ls="/bin/ls -Fh --color=auto"
alias	ll="/bin/ls -Flh --color=auto"
alias   ldir="/bin/ls -Falh --color | grep /$"
alias   lf="/bin/ls -Falh --color | grep ^-"
alias	l="less -R"
alias   vi="gvim -v"
alias   vim="gvim -v"
